### ISSUE TITLE
README.md: description mismatch

### ISSUE THREAD

**Issue by masaha03** [snd-lib/snd-lib#2]
In README.md, there seems to be some confusion about the description for "caution", "disabled", and "notification".

| name             | description            |
| ---------------- | ----------------- |
| caution | This sound is played when you press a disabled button. The sound is not as strong as the Caution sound described below. The sound is simply to indicate that the button itself is invalid. |
| disabled | This sound is played when you press a disabled button. The sound is not as strong as the Caution sound described below. The sound is simply to indicate that the button itself is invalid. |
| notification | A caution sound. This sound is played to indicate to the user that something is wrong, has a slightly more negative sound than Notification. |

"caution" and "disabled" have the same description.
The description of "notification" seems to be an description of "caution".

**Comment by snd-lib** [comment]
Thanks for pointing this out. We have corrected the description.
