### ISSUE TITLE
Loading Sound

### ISSUE THREAD

**Issue by manattweb** [snd-lib/snd-lib#3]
I cannot find in any of the documentation how to play the loading sound from javascript. I'm showing a loading div when a form is submitted while the data is processed via Ajax and I want the sound to be played during the time the div is shown. How is that done?

**Comment by snd-lib** [comment]
Thanks for your comment. We have prepared a sample code for the kind of behavior you are thinking of here on following codepen URL. I hope this will be helpful.

https://codepen.io/starryworks/pen/poZoqLX
